
import { GoogleGenAI } from "@google/genai";
import { ContentType, Tone } from "../types";

export const generateMarketingContent = async (
  type: ContentType,
  topic: string,
  tone: Tone,
  length: string,
  useSearch: boolean = false,
  additionalNotes: string = ""
): Promise<{text: string, sources?: any[]}> => {
  // Initialize right before call to ensure we have the latest environment state
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please check your environment configuration.");
  }
  
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const systemInstruction = `You are an expert marketing copywriter. 
  Generate high-converting content. If search results are provided, use them to include up-to-date facts.`;

  const prompt = `Generate a ${type} about: "${topic}".
  Tone: ${tone}
  Length: ${length}
  Notes: ${additionalNotes}`;

  try {
    const config: any = {
      systemInstruction,
      temperature: 0.7,
    };

    if (useSearch) {
      config.tools = [{ googleSearch: {} }];
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config,
    });

    return {
      text: response.text || "No content was generated by the model.",
      sources: response.candidates?.[0]?.groundingMetadata?.groundingChunks
    };
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    // Provide a more descriptive error message for the UI
    throw new Error(error?.message || "An unexpected error occurred during generation.");
  }
};

export const generateMarketingImage = async (prompt: string): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing for image generation.");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: `High quality professional marketing photography for: ${prompt}. Clean, commercial aesthetic, 4k.` }]
      },
      config: {
        imageConfig: { aspectRatio: "1:1" }
      }
    });

    let base64Data = "";
    let mimeType = "image/png";

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          base64Data = part.inlineData.data;
          mimeType = part.inlineData.mimeType;
          break;
        }
      }
    }

    if (base64Data) {
      return `data:${mimeType};base64,${base64Data}`;
    }
    
    throw new Error("The model did not return an image. Try a more descriptive topic.");
  } catch (error: any) {
    console.error("Image Generation Error:", error);
    throw new Error(error?.message || "Failed to generate image.");
  }
};
